{let startTime=new Date().getTime();const designWidth=1280;const designHeight=720;const bgWidth=1600;const bgHeight=720;const barBGWidth=1120;const barBGHeight=32;const barWidth=1114;const barHeight=27;const percentWidth=50;const percentHeight=36;const percentFontSize=22;const percentGap=10;const tipsWidth=700;const tipsFontSize=26;const tipsGap=-(24+barHeight);const tipsLineHeight=30;const showLogo=true;const logoWidth=535;const logoHeight=395;const el_bg=document.getElementById('lp_bg');const el_barbg=document.getElementById('lp_barbg');const el_barwrap=document.getElementById('lp_barwrap');const el_bar=document.getElementById('lp_bar');const el_percent=document.getElementById('lp_percent');const el_tips=document.getElementById('lp_tips');const LoadingPage=document.getElementById('LoadingPage');const el_logo=document.getElementById('lp_logo');if(showLogo==false){el_logo.remove();}
const tipList=[".","..","...","....",".....",]
class CLoadingPage{constructor(){this.containerWidth=window.innerWidth;this.containerHeight=window.innerHeight;this.curProgress=0.00;this.scale_bg=0;this.x_bg=0;this.y_bg=0;this.panelWidth=barBGWidth;this.scale_bar=0;this.barBottomY=330;this.panelLeft=0;this.tempScaleX=0;this.tempScaleY=0;this.panelScaledWidth=0;this.showBar=false;this.progressDuration=15;this.tickTime=1/30;this.tickAddProgress=1/this.progressDuration*this.tickTime;this.progressIntervalId=null;this.tipsIntervalId=null;this.tempCount=-1;this.tipsLength=tipList.length;this.firstCheck=true;this.checkDir();}
checkDir(){let userAgentInfo=window.navigator.userAgent;let Agents=['Android','iPhone','SymbianOS','Windows Phone','iPad','iPod'];let getArr=Agents.filter(i=>userAgentInfo.includes(i));const isMobile=getArr.length?true:false;let shuping=false;if(!isMobile){shuping=false;}else{const dir=window.orientation;if(dir==0&&180){shuping=true;}else{shuping=false;}}
if(shuping){LoadingPage.style.transformOrigin="left top";LoadingPage.style.msTransform="rotate(90deg)";LoadingPage.style.transform="rotate(90deg)";LoadingPage.style.left=window.innerWidth+'px';LoadingPage.style.height=window.innerWidth+'px';LoadingPage.style.width=window.innerHeight+'px';}else{LoadingPage.style.transformOrigin="left top";LoadingPage.style.msTransform="rotate(0deg)";LoadingPage.style.transform="rotate(0deg)";LoadingPage.style.left='0px';LoadingPage.style.height=window.innerHeight+'px';LoadingPage.style.width=window.innerWidth+'px';}
this.onResize();if(this.firstCheck){this.firstCheck=false;LoadingPage.style.visibility="visible";}}
fitBg(){this.tempScaleY=this.containerHeight/bgHeight;this.tempScaleX=this.containerWidth/bgWidth;this.scale_bg=this.tempScaleX>this.tempScaleY?this.tempScaleX:this.tempScaleY;this.x_bg=(this.containerWidth-bgWidth*this.scale_bg)/2;this.y_bg=(this.containerHeight-bgHeight*this.scale_bg)/2;el_bg.style.left=this.x_bg+"px";el_bg.style.top=this.y_bg+"px";el_bg.width=bgWidth*this.scale_bg;el_bg.height=bgHeight*this.scale_bg;}
fitBar(){this.panelWidth=barBGWidth;this.tempScaleY=this.containerHeight/designHeight;this.tempScaleX=this.containerWidth/designWidth;this.scale_bar=this.tempScaleX<this.tempScaleY?this.tempScaleX:this.tempScaleY;if(this.showBar==false){this.scale_bar=0;}
this.panelScaledWidth=barBGWidth*this.scale_bar;this.panelLeft=(this.containerWidth-this.panelScaledWidth)/2;el_barbg.style.left=this.panelLeft+"px";el_barbg.style.bottom=this.containerHeight/2-this.barBottomY*this.scale_bar+"px";el_barbg.width=barBGWidth*this.scale_bar;el_barbg.height=barBGHeight*this.scale_bar;el_bar.width=barWidth*this.scale_bar;el_bar.height=barHeight*this.scale_bar;el_barwrap.style.left=this.panelLeft+3*this.scale_bar+"px";el_barwrap.style.maxWidth=barWidth*this.scale_bar+"px";el_barwrap.style.height=barHeight*this.scale_bar+"px";el_barwrap.style.bottom=this.containerHeight/2-this.barBottomY*this.scale_bar+((barBGHeight-barHeight)/2)*this.scale_bar+"px";el_percent.style.left=this.panelLeft+barBGWidth*this.scale_bar/2-percentWidth*this.scale_bar/2+"px";el_percent.style.bottom=(this.containerHeight/2-this.barBottomY*this.scale_bar+(el_barbg.height-percentHeight)/2)+(1*this.scale_bar)+"px";el_percent.style.fontSize=percentFontSize*this.scale_bar+"px";if(showLogo){el_logo.width=logoWidth*this.scale_bar;el_logo.height=logoHeight*this.scale_bar;el_logo.style.top=this.containerHeight/2-el_logo.height/2-40*this.scale_bar+"px";el_logo.style.left=((this.containerWidth-logoWidth*this.scale_bar)/2)+"px";;}
this.setProgress(this.curProgress);}
fitTips(){el_tips.style.left=(this.containerWidth-tipsWidth*this.scale_bar)/2+"px";el_tips.style.bottom=this.containerHeight/2-this.barBottomY*this.scale_bar-tipsGap*this.scale_bar+"px";el_tips.style.width=tipsWidth*this.scale_bar+"px";el_tips.style.fontSize=tipsFontSize*this.scale_bar+"px";if(tipsLineHeight*this.scale_bar<tipsFontSize*this.scale_bar+10){el_tips.style.lineHeight=tipsFontSize*this.scale_bar+10+"px";}else{el_tips.style.lineHeight=tipsLineHeight*this.scale_bar+"px";}}
setProgress(progress){this.curProgress=progress;if(this.curProgress>1.0){this.curProgress=1.0;}
if(this.curProgress<0.0){this.curProgress=0.0;}
el_barwrap.style.width=barWidth*this.scale_bar*this.curProgress+"px";el_percent.textContent=(this.curProgress*100).toFixed(0)+"%";}
setTips(tipsStr){el_tips.textContent=tipsStr;this.fitTips();}
onResize(){if(LoadingPage.style.width!=""){this.containerWidth=Number(LoadingPage.style.width.replace('px',''));this.containerHeight=Number(LoadingPage.style.height.replace('px',''));}else{this.containerWidth=window.innerWidth;this.containerHeight=window.innerHeight;}
this.fitBg();this.fitBar();this.fitTips();}
start(){this.bindOnResize=this.checkDir.bind(this);this.bindOnOrientation=this.checkDir.bind(this);this.bindOnCocosFirstSceneShowed=this.onCocosFirstSceneShowed.bind(this);window.addEventListener('resize',this.bindOnResize);window.addEventListener("orientationchange",this.bindOnOrientation);document.addEventListener('CocosFirstSceneShowed',this.bindOnCocosFirstSceneShowed);this.onResize();setTimeout(this.onResize.bind(this),0);this.tipsIntervalId=setInterval(this.tipsIntervalFunc.bind(this),500);}
intervalFunc(){this.curProgress+=this.tickAddProgress;this.setProgress(this.curProgress);if(this.curProgress>=1.0){if(this.progressIntervalId){clearInterval(this.progressIntervalId);this.progressIntervalId=null;}}}
tipsIntervalFunc(){if(this.showBar==false){this.showBar=true;this.fitBar();}
if(++this.tempCount>=this.tipsLength){this.tempCount=0;}
this.setTips(tipList[this.tempCount]);}
removeLoadingPage(){if(this.bindOnResize){window.removeEventListener('resize',this.bindOnResize);}
if(this.bindOnOrientation){window.removeEventListener('orientationchange',this.bindOnOrientation);}
if(this.bindOnCocosFirstSceneShowed){document.removeEventListener('CocosFirstSceneShowed',this.bindOnCocosFirstSceneShowed);}
LoadingPage.remove();delete this;}
onCocosFirstSceneShowed(){this.curProgress=1.0;this.intervalFunc();setTimeout(this.removeLoadingPage.bind(this),200);if(this.tipsIntervalId){clearInterval(this.tipsIntervalId);this.tipsIntervalId=null;}
let endTime=new Date().getTime();console.log("enter first scene total use time:"+(endTime-startTime)+'ms');}}
const taskDownSize={["src/polyfills.bundle"]:14750,["src/system.bundle"]:36593,["src/import-map"]:54,["./../cocos-js/cc"]:6760814,["src/settings"]:33721,["assets/scripts/common/thirds/jszip"]:464844,["../src/chunks/bundle"]:5120,["assets/internal/config"]:5120,["assets/internal/index"]:5120,["assets/main/config"]:5120,["assets/main/index"]:1048576,["assets/resources/config"]:204800,["assets/resources/index"]:5120,}
const taskDownFileKeys=Object.keys(taskDownSize);function ___LPLOG___(...params){}
class PreloaderTaskCfg{constructor(name,path,cb){this.name=name;this.path=path;this.cb=cb;}}
class PreloaderNormalTask{constructor(cfg,parent=null){this.name=cfg.name;this.path=cfg.path;this.cb=cfg.cb;this.progressCb=null;this.size=0;this.parent=parent;for(let i=0,length=taskDownFileKeys.length;i<length;++i){if(this.path.includes(taskDownFileKeys[i])){this.size=taskDownSize[taskDownFileKeys[i]];break;}};this.curProgress=0;}
run(){___LPLOG___("      start download task ["+this.path+"]"+this.size);var req=new XMLHttpRequest();function onProgress(event){___LPLOG___("      normal Task ["+this.path+"] downloading",event.loaded);if(this.size>0){this.curProgress=(event.loaded/this.size);if(this.curProgress>1.0){this.curProgress=1.0;}
if(this.progressCb){this.progressCb(this.curProgress);}}}
function onFinish(event){___LPLOG___("      normal Task ["+this.path+"] download finish!",event.loaded);this.curProgress=1.0;if(this.progressCb){this.progressCb(this.curProgress);}
if(this.cb){this.cb(req.response);}
if(this.parent){this.parent.onChildFinish();}}
req.addEventListener("progress",onProgress.bind(this),false);req.addEventListener("loadend",onFinish.bind(this),false);req.open("GET",this.path);req.send();}}
class PreloaderMultiTask{constructor(name,taskCfgList,cb,progressCb){this.name=name;this.taskList=[];this.curProgress=0;this.cb=cb;this.progressCb=progressCb;this.finishCnt=0;this.taskCnt=taskCfgList.length;for(let i=0,length=taskCfgList.length;i<length;++i){this.taskList.push(new PreloaderNormalTask(taskCfgList[i],this));}}
run(){___LPLOG___("   MultiTask "+this.name+" start!!!");for(let i=0,length=this.taskList.length;i<length;++i){this.taskList[i].run();}}
onChildFinish(){this.finishCnt++;this.curProgress=this.finishCnt/this.taskCnt;if(this.curProgress>1.0){this.curProgress=1.0;}
if(this.progressCb){this.progressCb(this.curProgress);}
if(this.finishCnt>=this.taskCnt){___LPLOG___("   MultiTask "+this.name+" finish!!!");if(this.cb){this.cb();}}}
getProgress(){return this.curProgress;}}
class Preloader{constructor(){this.taskList=[];this.curProgress=0;this.perTaskProgress=0;this.depJSOK=false;this.ccDowned=false;}
start(){this.initTaskList();___LPLOG___('preload start!!!')
this.startTasks();}
addTask(taskObj){this.taskList.push(taskObj);}
onTaskProgress(taskProgress){this.curProgress=0;for(let i=0,length=this.taskList.length;i<length;++i){this.curProgress+=this.perTaskProgress*this.taskList[i].getProgress();}
LP_PageObj.setProgress(this.curProgress);}
onImportMapLoaded(){___LPLOG___("onImportMapLoaded!!!");var el_polyfills=document.createElement("script");el_polyfills.setAttribute("src","src/polyfills.bundle.5adbf.js");el_polyfills.setAttribute("charset","utf-8");document.documentElement.appendChild(el_polyfills);var el_system=document.createElement("script");el_system.setAttribute("src","src/system.bundle.692e9.js");el_system.setAttribute("charset","utf-8");document.documentElement.appendChild(el_system);var el_import=document.createElement("script");el_import.setAttribute("src","src/import-map.8f6ce.json");el_import.setAttribute("type","systemjs-importmap");el_import.setAttribute("charset","utf-8");document.documentElement.appendChild(el_import);setTimeout(()=>{this.depJSOK=true;if(this.ccDowned){this.onScriptDowned();}});}
onScriptDowned(){if(this.depJSOK){if(window['System']){let s=document.createElement("script");s.innerHTML="System.import('./index.21120.js').catch(function (err) { console.error(err); })";document.documentElement.appendChild(s);}else{setTimeout(this.onScriptDowned.bind(this));}}
this.ccDowned=true;}
initTaskList(){this.addTask(new PreloaderMultiTask('DepJs',[new PreloaderTaskCfg('polyfills','src/polyfills.bundle.5adbf.js'),new PreloaderTaskCfg('system','src/system.bundle.692e9.js'),new PreloaderTaskCfg('import','src/import-map.8f6ce.json'),],this.onImportMapLoaded.bind(this),this.onTaskProgress.bind(this)));this.addTask(new PreloaderMultiTask('CC',[new PreloaderTaskCfg('ccJs','./../cocos-js/cc.78d22.js'),new PreloaderTaskCfg('settingsJson','src/settings.536b4.json'),],this.onScriptDowned.bind(this),this.onTaskProgress.bind(this)));let pluginsJsList=[];let scriptPackages=["../src/chunks/bundle.0d920.js"];let cfgs=[];for(let i=0,length=pluginsJsList.length;i<length;++i){cfgs.push(new PreloaderTaskCfg(pluginsJsList[i],pluginsJsList[i]));}
for(let i=0,length=scriptPackages.length;i<length;++i){cfgs.push(new PreloaderTaskCfg(scriptPackages[i],scriptPackages[i]));}
this.addTask(new PreloaderMultiTask('pluginsJs and scriptPackages',cfgs,null,this.onTaskProgress.bind(this)));let preloadBundles=["assets/resources/config.8de02.json","assets/resources/index.8de02.js","assets/main/config.2d132.json","assets/main/index.2d132.js","assets/internal/config.10d6c.json","assets/internal/index.10d6c.js"];cfgs=[];for(let i=0,length=preloadBundles.length;i<length;++i){cfgs.push(new PreloaderTaskCfg(preloadBundles[i],preloadBundles[i]));}
this.addTask(new PreloaderMultiTask('preloadBundles',cfgs,null,this.onTaskProgress.bind(this)));this.perTaskProgress=1/this.taskList.length;}
startTasks(){for(let i=0,length=this.taskList.length;i<length;++i){this.taskList[i].run();}}}
LP_PageObj=new CLoadingPage();LP_PageObj.start();LP_LoaderObj=new Preloader();LP_LoaderObj.start();}